# AWS EC2 playbook to create a gitlab runner
---
- hosts: localhost
  connection: local
  gather_facts: false
  environment:
    # Ansible AWS modules
    AWS_ACCESS_KEY:        "{{ aws_provisioning_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_provisioning_secret_key }}"

    # AWS CLI
    AWS_ACCESS_KEY_ID:     "{{ aws_provisioning_access_key }}"
    AWS_DEFAULT_REGION:    "{{ vpc.region }}"

  roles:
    - name: "Create {{ vpc.name }} VPC"
      role: aws-vpc

    - name: "AWS gitlab common configuration"
      role: aws-gitlab-common

    - name: "AWS gitlab {{ gitlab_xl.runner_name }}"
      role: aws-gitlab
      vars:
        runner: "{{ gitlab_base | combine(gitlab_xl) }}"

    - name: "AWS gitlab {{ gitlab_micro.runner_name }}"
      role: aws-gitlab
      vars:
        runner: "{{ gitlab_base | combine(gitlab_micro) }}"

- hosts: gitlab_runner
  gather_facts: true
  roles:
    - name: Linux generic configuration
      role: common

    - name: Install docker
      role: docker

    - name: Install gitlab-runner
      role: gitlab-runner

  tasks:
    - name: Query restart required
      stat:
        path: /var/run/reboot-required
      register: stat_result

    - name: Reboot
      reboot:
        msg: "Ansible reboot"
      become: true
      when: stat_result.stat.exists
