- name: "Create IAM policy {{ docker_machine_spawn_iam_policy.name }}"
  iam_managed_policy:
    policy_name:        "{{ docker_machine_spawn_iam_policy.name }}"
    policy_description: "{{ docker_machine_spawn_iam_policy.description }}"
    policy:             "{{ docker_machine_spawn_iam_policy.policy_content }}"
    state:              present
  register:             iam_policy_info

- name: "Set fact docker_machine_spawn_iam_policy.policy_info"
  set_fact:
    docker_machine_spawn_iam_policy:
      "{{ docker_machine_spawn_iam_policy | combine({'policy_info':iam_policy_info.policy}) }}"
