- name: "Create IAM policy {{ gitlab_artifact_get_iam_policy.name }}"
  iam_managed_policy:
    policy_name:        "{{ gitlab_artifact_get_iam_policy.name }}"
    policy_description: "{{ gitlab_artifact_get_iam_policy.description }}"
    policy:             "{{ gitlab_artifact_get_iam_policy.policy_content }}"
    state:       present
  vars:
    s3_bucket:   "{{ gitlab_artifact }}"
  register: iam_policy_info

- name: "Set fact gitlab_artifact_get_iam_policy.policy_info"
  set_fact:
    gitlab_artifact_get_iam_policy:
      "{{ gitlab_artifact_get_iam_policy | combine({'policy_info':iam_policy_info.policy}) }}"
  vars:
    s3_bucket:   "{{ gitlab_artifact }}"

- name: "Create IAM policy {{ gitlab_artifact_put_iam_policy.name }}"
  iam_managed_policy:
    policy_name:        "{{ gitlab_artifact_put_iam_policy.name }}"
    policy_description: "{{ gitlab_artifact_put_iam_policy.description }}"
    policy:             "{{ gitlab_artifact_put_iam_policy.policy_content }}"
    state:       present
  vars:
    s3_bucket:   "{{ gitlab_artifact }}"
  register: iam_policy_info

- name: "Set fact gitlab_artifact_put_iam_policy.policy_info"
  set_fact:
    gitlab_artifact_put_iam_policy:
      "{{ gitlab_artifact_put_iam_policy | combine({'policy_info':iam_policy_info.policy}) }}"
  vars:
    s3_bucket:   "{{ gitlab_artifact }}"
