- name: "Create EC2 security group {{ gitlab_runner_security_group.name }}"
  ec2_group:
    name:        "{{ gitlab_runner_security_group.name }}"
    description: "{{ gitlab_runner_security_group.description }}"
    vpc_id:      "{{ vpc.vpc_info.id }}"
    region:      "{{ vpc.region }}"
    tags:        "{{ vpc.tags }}"
    rules:       "{{ gitlab_runner_security_group.rules }}"
  register: ec2_group_info

- name: "Set fact gitlab_runner_security_group.group_info"
  set_fact:
    gitlab_runner_security_group:
      "{{ gitlab_runner_security_group | combine({'group_info':ec2_group_info}) }}"

- name: "Create EC2 security group {{ docker_machine_instance_security_group.name }}"
  ec2_group:
    name:        "{{ docker_machine_instance_security_group.name }}"
    description: "{{ docker_machine_instance_security_group.description }}"
    vpc_id:      "{{ vpc.vpc_info.id }}"
    region:      "{{ vpc.region }}"
    tags:        "{{ vpc.tags }}"
    rules:       "{{ docker_machine_instance_security_group.rules }}"
  register: ec2_group_info

- name: "Set fact docker_machine_instance_security_group.group_info"
  set_fact:
    docker_machine_instance_security_group:
      "{{ docker_machine_instance_security_group | combine({'group_info':ec2_group_info}) }}"

- name: Create EC2 key pair {{ gitlab_base.runner_key_name }}
  ec2_key:
    name:          "{{ gitlab_base.runner_key_name }}"
    key_material:  "{{ lookup('file', gitlab_base.runner_key_file_public) }}"
    region:        "{{ vpc.region }}"
