---
- name: Configure EC2 {{ app }}
  include_tasks: common-ec2.yml

- name: Configure IAM docker-machine
  include_tasks: docker-machine-iam.yml

- name: Configure IAM {{ gitlab_artifact }}
  include_tasks: gitlab-artifact-iam.yml

- name: Configure S3 {{ gitlab_artifact }}
  include_tasks: gitlab-artifact-s3.yml

- name: Configure IAM gitlab
  include_tasks: gitlab-build-iam.yml

- name: Configure EC2 gitlab
  include_tasks: gitlab-build-ec2.yml
