gitlab_runner:   "{{ org }}-{{ app }}-runner"
gitlab_machine:  "{{ org }}-{{ app }}-machine"
gitlab_artifact: "{{ org }}-{{ app }}-artifact"
docker_machine_gen_cert_sg: ""  # determined at runtime

gitlab_base:
  runner_config_template:   "gitlab-build.toml"
  # TODO: If you have VPN configured, you can restrict this to your private subnet.
  runner_subnet:            "{{ public_subnet }}"
  runner_executor:          "docker+machine"
  runner_instance_type:     "t3.nano"
  runner_ami:               "ami-02ae530dacc099fc9"  # Amazon ubuntu 20.04 amd64 server
  runner_iam_role_name:     "{{ gitlab_runner_iam_role.role_info.role_name }}"
  runner_security_groups:
    - "{{ gitlab_runner_security_group.group_info.group_id }}"
    - "{{ vpc_ssh_security_group.group_info.group_id }}"
    - "{{ vpc_icmp_security_group.group_info.group_id }}"
    # TODO: These rules are here for diagnostics. They open ICMP and SSH for
    # any network. If you have VPN configured, remove these.
    - "{{ public_ssh_security_group.group_info.group_id }}"
    - "{{ public_icmp_security_group.group_info.group_id }}"
  runner_key_name:          "{{ gitlab_runner }}"
  runner_key_file_public:   "files/gitlab-build.pub"
  runner_key_file_private:  "files/gitlab-build"
  machine_subnet:              "{{ private_subnet }}"
  machine_iam_policy_name:     "{{ gitlab_machine_iam_role.name }}"
  machine_security_group_name: "{{ docker_machine_instance_security_group.name }}"
  machine_idle_count:       0
  machine_idle_time:        3600
  concurrent: 1
  ansible_groups:
    - gitlab_runner
    - docker_machine

# gitlab-runner-compiler-xl variables
# variables here will be combined with the base variables
# so that base variables are 'overridden'
gitlab_xl:
  runner_name:              "{{ gitlab_runner }}-xl"
  runner_tags:
    - docker
    - autoscale
    - compiler-xl
  machine_name:             "{{ gitlab_runner }}-xl-machine"
  machine_instance_type:    "c5.9xlarge"
  concurrent:               10

# gitlab-runner-compiler-micro variables
# variables here will be combined with the base variables
# so that base variables are 'overridden'
gitlab_micro:
  runner_name:              "{{ gitlab_runner }}-micro"
  runner_tags:
    - docker
    - autoscale
    - compiler-micro
  machine_name:             "{{ gitlab_runner }}-micro-machine"
  machine_instance_type:    "t3.micro"
  machine_idle_time:        7200
  concurrent:               10

gitlab_metrics_server_port: 9252
gitlab_session_server_port: 8093
