---
- name: Check internet connectivity
  wait_for: host=google.com port=80 timeout=10

- name: Update apt cache
  apt:
    update_cache: true
  become: true
  changed_when: false # not an interesting change

- name: Upgrade packages
  apt:
    upgrade: safe
  become: true

- name: Upgrade distribution
  apt:
    upgrade: dist
  become: true
