[[runners]]
  name = "{{ runner.runner_name }}"
  environment = ["DOCKER_AUTH_CONFIG={{ docker_auth }}"]
  limit = 16
  [runners.docker]
    tls_verify = true
    privileged = false  # privileged is a security risk
    disable_entrypoint_overwrite = false
  [runners.machine]
    IdleCount = {{ runner.machine_idle_count }}
    IdleTime = {{ runner.machine_idle_time }}
    MaxBuilds = 100
    MachineDriver = "amazonec2"
    MachineName = "{{ app }}-%s"  # must be short; hostname
    MachineOptions = [
      # docker-machine has a built-in AWS SDK client that
      # will query container metadeta for AWS credentials
      # provided in an IAM instance profile role. This is
      # not documented via gitlab, but is more secure than
      # storing static AWS credentials in the runner. The
      # following machine options should be omitted:
      #    amazonec2-access-key
      #    amazonec2-secret-key
      "amazonec2-region={{ vpc.region }}",
      "amazonec2-zone={{ vpc.zone }}",
      "amazonec2-vpc-id={{ vpc.vpc_info.id }}",
      "amazonec2-subnet-id={{ runner.machine_subnet.subnet_info.id }}",
      "amazonec2-retries=10",
      "amazonec2-use-private-address=true",
      "amazonec2-private-address-only=true",
      "amazonec2-tags=app,{{ app }},Name,{{ runner.machine_name }},gitlab-machine,{{ app }}",
      "amazonec2-security-group={{ runner.machine_security_group_name }}",
      "amazonec2-instance-type={{ runner.machine_instance_type }}",
      "amazonec2-iam-instance-profile={{ runner.machine_iam_policy_name }}"
    ]
