---
- name: Add docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  become: true

- name: Add docker apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
  become: true

- name: Install docker-ce
  apt:
    pkg: docker-ce
    state: latest
    update_cache: true
  become: true
  register: apt_docker_ce

- name: Install docker module for python
  pip:
    name: docker
    state: latest
  become: true
