docker_machine_spawn_iam_policy:
  name:           "docker-machine-spawn"
  description:    "Spawn EC2 instances and pass IAM roles to docker-machines"
  policy_info:    {}   # fact set from EC2 query
  policy_content: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": [
            "ec2:StartInstances",
            "ec2:RunInstances",
            "ec2:DescribeInstances",
            "ec2:RebootInstances",
            "ec2:StopInstances",
            "ec2:TerminateInstances",

            "ec2:CreateTags",

            "ec2:DescribeKeyPairs",
            "ec2:ImportKeyPair",
            "ec2:CreateKeyPair",
            "ec2:DeleteKeyPair",

            "ec2:DescribeSubnets",
            "ec2:DescribeSecurityGroups"
          ],
          "Resource": "*"
        }
      ]
    }
