# TODO: If you have VPN into your VPC, or if otherwise
# the runner is inside your private subnet, remove
# "public_subnet.cidr" from the rules below.
docker_machine_instance_security_group:
  name: "docker-machine-instance"
  description: "docker-machine spawned host"
  group_info: {}   # fact set after EC2 query
  rules:
    - proto: tcp
      ports:
        - 22
      cidr_ip:
        - "{{ private_subnet.cidr }}"
        - "{{ public_subnet.cidr }}"
      rule_desc: SSH
    - proto: tcp
      ports:
        - 2376
      cidr_ip:
        - "{{ private_subnet.cidr }}"
        - "{{ public_subnet.cidr }}"
      rule_desc: "docker machine"
