gitlab_runner_iam_role:
  name: "{{ gitlab_runner }}"
  description: "Gitlab autoscale runner to spawn docker-machines and pass deploy roles."
  role_info: {}  # fact set by AWS query
  trust_content: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect":    "Allow",
          "Action":    "sts:AssumeRole",
          "Principal":
          {
            "Service": "ec2.amazonaws.com"
          }
        }
      ]
    }
  managed_policy:
    - "{{ docker_machine_spawn_iam_policy.policy_info.arn }}"
    - "{{ gitlab_machine_passrole_iam_policy.policy_info.arn }}"
