gitlab_machine_passrole_iam_policy:
  name:           "{{ gitlab_machine }}-passrole"
  description:    "Pass IAM instance role to spawned machines."
  policy_info:    {}   # fact set from EC2 query
  policy_content: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Effect": "Allow",
          "Action": "iam:PassRole",
          "Resource": "{{ gitlab_machine_iam_role.role_info.arn }}"
        }
      ]
    }
