gitlab_runner_security_group:
  name: "gitlab-runner"
  description: "gitlab runner metrics and session services"
  group_info: {}   # fact set after EC2 query
  rules:
    - proto: tcp
      ports:
        - "{{ gitlab_metrics_server_port }}"
      cidr_ip:
        - "{{ private_subnet.cidr }}"
      rule_desc: "gitlab metrics server"
    - proto: tcp
      ports:
        - "{{ gitlab_session_server_port }}"
      cidr_ip: 0.0.0.0/0
      rule_desc: "gitlab session server"
