gitlab_artifact_put_iam_policy:
  name:           "{{ gitlab_artifact }}-put"
  description:    "Put artifacts to S3"
  policy_info:    {}   # fact set from EC2 query
  policy_content: |
    {
      "Version": "2012-10-17",
      "Statement": [
        {
          "Action": [
              "s3:PutObject"
          ],
          "Effect": "Allow",
          "Resource": "arn:aws:s3:::{{ gitlab_artifact }}/*"
        }
      ]
    }
