public_ssh_security_group:
  name: "public-ssh"
  description: "public SSH access"
  group_info: {}   # fact set after EC2 query
  rules:
    - proto: tcp
      ports:
        - 22
      cidr_ip: 0.0.0.0/0
      rule_desc: SSH
