vpc_ssh_security_group:
  name: "{{ vpc.name }}-ssh"
  description: "SSH access from VPC {{ vpc.name }}"
  group_info: {}   # fact set after EC2 query
  rules:
    - proto: tcp
      ports:
        - 22
      cidr_ip:
        - "{{ vpc.cidr }}"
      rule_desc: SSH
