---
- name: Install docker-machine
  get_url:
    url:   "https://github.com/docker/machine/releases/download/v0.16.0/docker-machine-{{ ansible_system }}-{{ ansible_architecture }}"
    dest:  /usr/local/bin/docker-machine
    mode:  u+x,g+x
    group: gitlab-runner
    owner: gitlab-runner
  become: true
  register: docker_machine_install
