---

- name: List registered gitlab runners
  # gitlab-runner list writes standard outout to stderr (wtf?)
  shell: "gitlab-runner list 2>&1 | grep {{ runner.runner_name }} | cut -f1 -d' '"
  become: true
  register: result
  failed_when: false
  changed_when: false

# gitlab-runner register is not idempotent. A better solution
# would be to use the gitlab-runner API to query existing
# runners and add/remove by tag names but this is potentially
# brittle and error-prone. To achieve idempotency-ish behavior,
# simply remove previosly registered runners and re-register them.
- name: Remove previously registered runners
  command: gitlab-runner unregister --name {{ item | quote }}
  become:  true
  with_items: "{{ result.stdout_lines }}"

- name: Register gitlab runner
  command: >
    gitlab-runner register
      --non-interactive
      --url https://gitlab.com
      --registration-token "{{ gitlab_runner_registration_token }}"
      --executor "{{ runner.runner_executor }}"
      --docker-image "docker:latest"
      --description "{{ runner.runner_name }}"
      --tag-list "{{ runner.runner_tags | join(',')}},{{ runner.runner_name }}"
      --template-config /etc/gitlab-runner/runner-config-template.toml
  become: true
