---

- name: Add gitlab GPG key
  apt_key:
    url: "https://packages.gitlab.com/runner/gitlab-runner/gpgkey"
  become: true

- name: Add gitlab apt repository
  apt_repository:
    repo: deb https://packages.gitlab.com/runner/gitlab-runner/ubuntu/ {{ansible_distribution_release}} main
  become: true

- name: Install gitlab-runner
  apt:
    pkg: gitlab-runner
    update_cache: true
  become: true
  register: apt_gitlab_runner

- name: Install python-gitlab
  pip:
    name: python-gitlab
  become: yes

- name: Install gitlab-cli
  apt:
    name: gitlab-cli
  become: true

- name: Add gitlab-runner to docker group
  user:
    name: gitlab-runner
    groups:
      - docker
    append: true
  become: true
  register: docker_group

# yes you really need to do this, since Ansible
# connects over an SSH session, it's the most
# sure-fire way to ensure permissions take effect
# for something like docker that runs as a service.
- name: Reboot on user group change
  reboot:
    msg: "Ansible reboot"
  become: true
  when: docker_group.changed
