- name: Install gitlab-runner
  include_tasks: gitlab-install.yml

- name: Instal docker-machine
  when: runner.runner_executor == "docker+machine"
  block:
    - name: Install docker-machine
      include_tasks: docker-machine.yml

    - name: Configure docker-machine TLS
      include_tasks: docker-machine-tls.yml

- name: Configure gitlab-runner
  include_tasks: gitlab-configure.yml

- name: Query gitlab runner registration
  command: gitlab-runner verify --name {{ runner.runner_name }}
  become: true
  changed_when: false
  failed_when: false
  register: gitlab_runner_verify

- name: Register gitlab-runner
  include_tasks: gitlab-register.yml
  when: (gitlab_runner_verify.stderr.find('ERROR') != -1)
        or (gitlab_runner_verify.rc != 0)

- name: Verify gitlab runner
  command: gitlab-runner verify --name {{ runner.runner_name }}
  changed_when: false
  become: true

- name: Query gitlab-runner service status
  command: gitlab-runner status
  become: true
  changed_when: false
  failed_when: false
  register: gitlab_runner_status

- name: Start gitlab-runner service
  command: gitlab-runner start
  become: true
  when: gitlab_runner_status.rc != 0
